<a href="https://colab.research.google.com/github/JoaoCuri/pequenos_desafios/blob/master/Numpy_Arrays_e_estatistica_basica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy


O Numpy" foi construído para facilitar facilita a execução de cálculos com os dados que estão armazenados em "arrays" e matrizes, mesmo que você tem uma quantidade gigante de dados.

Arrays e Numpy

In [7]:
import numpy as np
from numpy.random import random


In [8]:
np.set_printoptions(precision=2)

criando um array

In [9]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [13]:
np.random.seed(25)
b = np.random.randn(6)
b

array([ 0.23,  1.03, -0.84, -0.59, -0.96, -0.22])

## maioria dos metodos no numpy tem como resultados Arrays

fazendo operações com arrays

In [14]:
c = np.arange(1,35)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [15]:
a + b

array([1.23, 3.03, 2.16, 3.41, 4.04, 5.78])

In [16]:
a*10

array([10, 20, 30, 40, 50, 60])

In [17]:
a/b

array([  4.38,   1.95,  -3.57,  -6.77,  -5.23, -26.99])

In [18]:
a-b

array([0.77, 0.97, 3.84, 4.59, 5.96, 6.22])

## martizes

multiplicação de matrizes e arrays

In [22]:
a = np.arange(3)
aa = np.array([[2.,4.,6.],[1.,3.,5.],[10.,20.,30.]])
aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [23]:
a*aa

array([[ 0.,  4., 12.],
       [ 0.,  3., 10.],
       [ 0., 20., 60.]])

multiplicando matrizes

In [24]:
bb = np.arange(9).reshape((3,3))
bb

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
aa * bb # essa não é a multiplicação que conhecemos aqui o python só multiplicou item a item

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

In [26]:
# multiplicação real
np.dot(aa,bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])

In [28]:
b = a*3
b

array([0, 3, 6])

In [29]:
np.dot(a,b) #para calcular o produto escalar de a * b

15

## Estatística descritiva

*   **Descrevendo as observações de uma variável:** soma,mediana,média e máximo.
*   **Descrevendo a dispersão de uma variável:** Desvio padrão, variancia, contagens e quartis.



>#### Usos da estatística descritiva

>*   deteção de outliers
>*   Planejar os requisitos de preparação dos dados para pré-processamento
>*   Escolher variáveis para uso em machine learning





## Matematica e estatistica básica 

investigando valores numericos

In [1]:
import pandas as pd


In [2]:
url = 'https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv'

In [4]:
carros = pd.read_csv(url)
carros.head()

model   mpg  cyl   disp   hp  ...   qsec  vs  am  gear  carb
0          Mazda RX4  21.0    6  160.0  110  ...  16.46   0   1     4     4
1      Mazda RX4 Wag  21.0    6  160.0  110  ...  17.02   0   1     4     4
2         Datsun 710  22.8    4  108.0   93  ...  18.61   1   1     4     1
3     Hornet 4 Drive  21.4    6  258.0  110  ...  19.44   1   0     3     1
4  Hornet Sportabout  18.7    8  360.0  175  ...  17.02   0   0     3     2

[5 rows x 12 columns]

In [5]:
# somatório
carros.sum

<bound method DataFrame.sum of                   model   mpg  cyl   disp   hp  ...   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110  ...  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110  ...  17.02   0   1     4     4
2            Datsun 710  22.8    4  108.0   93  ...  18.61   1   1     4     1
3        Hornet 4 Drive  21.4    6  258.0  110  ...  19.44   1   0     3     1
4     Hornet Sportabout  18.7    8  360.0  175  ...  17.02   0   0     3     2
5               Valiant  18.1    6  225.0  105  ...  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0  245  ...  15.84   0   0     3     4
7             Merc 240D  24.4    4  146.7   62  ...  20.00   1   0     4     2
8              Merc 230  22.8    4  140.8   95  ...  22.90   1   0     4     2
9              Merc 280  19.2    6  167.6  123  ...  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123  ...  18.90   1   0     4     4
11           Merc 450

In [7]:
carros.sum(axis = 1) #assim opandas faz a soma linha a linha

0     328.980
1     329.795
2     259.580
3     426.135
4     590.310
5     385.540
6     656.920
7     270.980
8     299.570
9     350.460
10    349.660
11    510.740
12    511.500
13    509.850
14    728.560
15    726.644
16    725.695
17    213.850
18    195.165
19    206.955
20    273.775
21    519.650
22    506.085
23    646.280
24    631.175
25    208.215
26    272.570
27    273.683
28    670.690
29    379.590
30    694.710
31    288.890
dtype: float64

Mediana

In [8]:
carros.median()

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [9]:
carros.mean()

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [10]:
carros.max()

model    Volvo 142E
mpg            33.9
cyl               8
disp            472
hp              335
drat           4.93
wt            5.424
qsec           22.9
vs                1
am                1
gear              5
carb              8
dtype: object

In [12]:
carros['mpg'].idxmax()

19

Aqui descobrimos que a linha 19 é a que apresanta o maior valor para a variável mpg.